# License terms and conditions for the Favorite Tree API:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-cm
  namespace: {{ .Release.Namespace }}
  labels:
    APP_NAME: tree-api
{{ include "tree-api.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
data:
  FLASK_APP: {{ .Values.configmap.flaskApp }}
  FLASK_ENV: {{ .Values.configmap.flaskEnv }}
  GUNICORN_LOG_LEVEL: {{ .Values.configmap.guncornLogLevel }}
  SQLALCHEMY_DATABASE_URI_FILEPATH: {{ .Values.configmap.sqlalchemyDatabaseUriFilepath }}
