{{ if .Values.ingress.nginx.enabled -}}
{{ $fullName := include "tree-api.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-tree-api
  labels:
    app: {{ $fullName }}-tree-api
{{- if .Values.ingress.treeApiLabels }}
{{ toYaml .Values.ingress.treeApiLabels | indent 4 }}
{{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.nginx.ingresClass }}
    {{- if .Values.hack.enabled }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {return 200;{"tree":{"favorite":"{{.Values.hack.favoriteTree }}"}};}
    {{- end }}
{{- if .Values.ingress.treeApiAdditionalAnnotations }}
{{ toYaml .Values.ingress.treeApiAdditionalAnnotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  {{- $host := . -}}
  {{- with $ }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /tree
            pathType: Exact
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
  {{- end }}
  {{- end }}
{{- end }}