apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    APP_NAME: tree-api
{{ include "tree-api.labels" . | indent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.additionalAnnotations }}
  annotations:
{{ toYaml .Values.additionalAnnotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.alb.enabled }}
  type: NodePort
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    name: {{ .Values.service.name }}
  selector:
    app: {{ .Release.Name }}-{{ include "tree-api.name" . }} #tree-api
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
{{ toYaml . | indent 4 }}
  {{- end }}
